[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

# Program IDs - Deployed to Devnet on 2026-01-21
[programs.localnet]
velo_mixer = "DSQt1z5wNcmE5h2XL1K1QAWHy28iJufg52aGy3kn8pEc"
velo_private_tx = "11111111111111111111111111111111"
velo_subscription = "11111111111111111111111111111111"
velo_stealth = "11111111111111111111111111111111"

[programs.devnet]
velo_mixer = "DSQt1z5wNcmE5h2XL1K1QAWHy28iJufg52aGy3kn8pEc"
velo_private_tx = "11111111111111111111111111111111"
velo_subscription = "11111111111111111111111111111111"
velo_stealth = "11111111111111111111111111111111"

[programs.mainnet]
velo_mixer = "DSQt1z5wNcmE5h2XL1K1QAWHy28iJufg52aGy3kn8pEc"
velo_private_tx = "11111111111111111111111111111111"
velo_subscription = "11111111111111111111111111111111"
velo_stealth = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "velo_mixer",
    "velo_private_tx",
    "velo_subscription",
    "velo_stealth"
]
