[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

# Program IDs - Deployed to Devnet on 2026-01-21
[programs.localnet]
velo = "AQgeVtAYEvigMbBW5gEiK4voELjFB94fDY9cFZqKHgZ8"
velo_mixer = "DSQt1z5wNcmE5h2XL1K1QAWHy28iJufg52aGy3kn8pEc"

[programs.devnet]
velo = "AQgeVtAYEvigMbBW5gEiK4voELjFB94fDY9cFZqKHgZ8"
velo_mixer = "DSQt1z5wNcmE5h2XL1K1QAWHy28iJufg52aGy3kn8pEc"

[programs.mainnet]
velo = "AQgeVtAYEvigMbBW5gEiK4voELjFB94fDY9cFZqKHgZ8"
velo_mixer = "DSQt1z5wNcmE5h2XL1K1QAWHy28iJufg52aGy3kn8pEc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "velo",
    "velo_mixer"
]
